adding solution to task8
sharontakhar/be-nc-news pull request #8
Opened 2022-08-04 15:38 UTC by sharontakhar

hello, please can i submit by solution to task 8 please,

i have names the functions getArticles/selectArticles

2022-08-04 16:05 UTC, alexdevdavis requested changes
as per comments, your query should group and/or sort by whatever variables are passed into the function

2022-08-04 16:05 UTC, alexdevdavis commented on __tests__/index.test.js
> +        expect(response.body.articles[0]).toEqual(
this test doesn't test the order of the res.body array: you're going to need jest sorted npm package to get this done efficiently

2022-08-04 16:05 UTC, alexdevdavis commented on models/models.js
> +      "SELECT articles.*, CAST(COUNT(comments.article_id)AS INT) AS comment_count FROM articles LEFT JOIN comments ON articles.article_id = comments.article_id GROUP BY articles.article_id ORDER BY a
your db query should change as a result of arguments passed into this function (drawn from req.params)
you'll also need to use <array variable>.includes to protect against SQL injection.

I'd suggest having a look through the notes for this one

2022-08-05 13:30 UTC, k-huggs commented
merge!

2022-08-05 13:54 UTC, merged